#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname compilemodel -pa ebin -config ./priv/compilemodel.config
main([]) ->
    Path = application:get_env(compilemodel),
    Result = erldb_compiler:compile(Path),
    io:format("Compiled:  ~p~n", [Result]).
