#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname compilemodel -pa ebin deps/erldb/ebin
main(Args) ->
    App = list_to_atom(hd(Args)),
    application:load(App),
    case application:get_env(App, model_path) of
	{ok, Path} ->
	    io:format("model_path: ~p~n", [Path]),
	    erldb_log:msg("Start compiling", ""),
	    case filelib:is_dir("./include") of
		true -> ok;
		false -> file:make_dir("./include")
	    end,
	    {ok, Filenames} = file:list_dir(Path),
	    compile_models(Filenames, Path),
	    erldb_log:msg("Done compiling", "");
	undefined ->
	    ok
    end.	    

compile_models([], _) ->
    ok;
compile_models([H|T], Path) ->
    Result = erldb_compiler:compile(filename:join([Path, H]),
				    [{includedir, "./include"},
				     {outdir, "./ebin"}]),
    io:format("~p... ~p~n", [H, Result]),
    compile_models(T, Path).
