name: Erlang CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp: [22.1, 20.3.8.22]
    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.0.0
      with:
        otp-version: ${{matrix.otp}}
    - name: Compile
      run: rebar3 compile
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run xref
      run: rebar3 xref
    - name: Run elvis
      run: rebar3 as lint lint
